# Generated by Django 2.0 on 2018-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ccv', models.CharField(blank=True, max_length=3, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=200)),
                ('pin', models.CharField(blank=True, max_length=4)),
                ('amount', models.CharField(blank=True, max_length=10)),
                ('ref', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
